---
###############################################################################
# Role    : security
# File    : firewalld.yml
# Purpose : Configure Enterprise Firewall
# Author  : Rajasekhar Miriyala
###############################################################################

- name: Install firewalld
  ansible.builtin.package:
    name: firewalld
    state: present

- name: Enable and start firewalld
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true

- name: Allow required services
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  loop: "{{ firewalld_services }}"
  notify: Reload firewalld

- name: Collect service facts
  ansible.builtin.service_facts:

- name: Validate firewalld service
  ansible.builtin.assert:
    that:
      - ansible_facts.services['firewalld.service'].state == 'running'
    fail_msg: "Firewalld is not running."
    success_msg: "Firewalld is running."